// This file contains the data for the SP-404MKII effects,
// adapted from the original Max for Live device files.

const fxData = {
  oneTwo: [
    "_parameter_range",
    "(OFF)",
    "Direct FX1",
    "Direct FX2",
    "Direct FX3",
    "Direct FX4",
    "Direct FX5",
    "Scatter",
    "Downer",
    "Ha-Dou",
    "Ko-Da-Ma",
    "Zan-Zou",
    "To-Gu-Ro",
    "SBF",
    "Stopper",
    "Tape Echo",
    "TimeCtrlDly",
    "Super Filter",
    "WrmSaturator",
    "303 VinylSim",
    "404 VinylSim",
    "Cassette Sim",
    "Lo-fi",
    "Reverb",
    "Chorus",
    "JUNO Chorus",
    "Flanger",
    "Phaser",
    "Wah",
    "Slicer",
    "Tremolo/Pan",
    "Chromatic PS",
    "Hyper-Reso",
    "Ring Mod",
    "Crusher",
    "Overdrive",
    "Distortion",
    "Equalizer",
    "Compressor",
    "SX Reverb",
    "SX Delay",
    "Cloud Delay",
    "Back Spin",
  ],
  threeFour: [
    "_parameter_range",
    "(OFF)",
    "303 VinylSim",
    "404 VinylSim",
    "Cassette Sim",
    "Lo-fi",
    "Downer",
    "Compressor",
    "Equalizer",
    "Isolator",
    "Super Filter",
    "Filter+Drive",
    "WrmSaturator",
    "Overdrive",
    "Distortion",
    "Crusher",
    "Ring Mod",
    "SBF",
    "Resonator",
    "Hyper-Reso",
    "Chromatic PS",
    "Reverb",
    "Ha-Dou",
    "Zan-Zou",
    "Sync Delay",
    "TimeCtrlDly",
    "Ko-Da-Ma",
    "Tape Echo",
    "Chorus",
    "JUNO Chorus",
    "Flanger",
    "Phaser",
    "Wah",
    "Slicer",
    "Tremolo/Pan",
    "To-Gu-Ro",
    "DJFX Looper",
    "Scatter",
    "SX Reverb",
    "SX Delay",
    "Cloud Delay",
  ],
  input: [
    "_parameter_range",
    "(OFF)",
    "Auto Pitch",
    "Vocoder",
    "Harmony",
    "GT Amp Sim",
    "Chorus",
    "JUNO Chorus",
    "Reverb",
    "TimeCtrlDly",
    "Chromatic PS",
    "Downer",
    "WrmSaturator",
    "303 VinylSim",
    "404 VinylSim",
    "Cassette Sim",
    "Lo-fi",
    "Equalizer",
    "Compressor",
  ],
};

const fxParams = {
  "(Off)": {},
  "Filter+Drive": {
    0: { name: "Cutoff", cc: 16 },
    1: { name: "Resonance", cc: 17 },
    2: { name: "Drive", cc: 18 },
    3: { name: "Flt Type", cc: 80 },
    4: { name: "Low Freq", cc: 81 },
    5: { name: "Low Gain", cc: 82 },
  },
  Resonator: {
    0: { name: "Root", cc: 16 },
    1: { name: "Bright", cc: 17 },
    2: { name: "Feedback", cc: 18 },
    3: { name: "Chord", cc: 80 },
    4: { name: "Panning", cc: 81 },
    5: { name: "Env Mod", cc: 82 },
  },
  "Sync Delay": {
    0: { name: "Time", cc: 16 },
    1: { name: "Feedback", cc: 17 },
    2: { name: "Level", cc: 18 },
    3: { name: "L Damp F", cc: 80 },
    4: { name: "H Damp F", cc: 81 },
  },
  Isolator: {
    0: { name: "Low", cc: 16 },
    1: { name: "Mid", cc: 17 },
    2: { name: "High", cc: 18 },
  },
  "DJFX Looper": {
    0: { name: "Length", cc: 16 },
    1: { name: "Speed", cc: 17 },
    2: { name: "Loop Sw", cc: 18 },
  },
  Scatter: {
    0: { name: "Type", cc: 16 },
    1: { name: "Depth", cc: 17 },
    2: { name: "Scatter", cc: 18 },
    3: { name: "Speed", cc: 80 },
  },
  Downer: {
    0: { name: "Depth", cc: 16 },
    1: { name: "Rate", cc: 17 },
    2: { name: "Filter", cc: 18 },
    3: { name: "Pitch", cc: 80 },
    4: { name: "Resonance", cc: 81 },
  },
  "Ha-Dou": {
    0: { name: "Mod Depth", cc: 16 },
    1: { name: "Time", cc: 17 },
    2: { name: "Level", cc: 18 },
    3: { name: "Low Cut", cc: 80 },
    4: { name: "High Cut", cc: 81 },
    5: { name: "Pre Delay", cc: 82 },
  },
  "Ko-Da-Ma": {
    0: { name: "Time", cc: 16 },
    1: { name: "Feedback", cc: 17 },
    2: { name: "Send", cc: 18 },
    3: { name: "L Damp F", cc: 80 },
    4: { name: "H Damp F", cc: 81 },
    5: { name: "Mode", cc: 82 },
  },
  "Zan-Zou": {
    0: { name: "Time", cc: 16 },
    1: { name: "Feedback", cc: 17 },
    2: { name: "HF Damp", cc: 18 },
    3: { name: "Level", cc: 80 },
    4: { name: "Mode", cc: 81 },
    5: { name: "Sync", cc: 82 },
  },
  "To-Gu-Ro": {
    0: { name: "Depth", cc: 16 },
    1: { name: "Rate", cc: 17 },
    2: { name: "Resonance", cc: 18 },
    3: { name: "Flt Mod", cc: 80 },
    4: { name: "Amp Mod", cc: 81 },
    5: { name: "Sync", cc: 82 },
  },
  SBF: {
    0: { name: "Interval", cc: 16 },
    1: { name: "Width", cc: 17 },
    2: { name: "Balance", cc: 18 },
    3: { name: "Type", cc: 80 },
    4: { name: "Gain", cc: 81 },
  },
  Stopper: {
    0: { name: "Depth", cc: 16 },
    1: { name: "Rate", cc: 17 },
    2: { name: "Resonance", cc: 18 },
    3: { name: "Flt Mod", cc: 80 },
    4: { name: "Amp Mod", cc: 81 },
  },
  "Tape Echo": {
    0: { name: "Time", cc: 16 },
    1: { name: "Feedback", cc: 17 },
    2: { name: "Level", cc: 18 },
    3: { name: "Mode", cc: 80 },
    4: { name: "W/F Rate", cc: 81 },
    5: { name: "W/F Depth", cc: 82 },
  },
  TimeCtrlDly: {
    0: { name: "Time", cc: 16 },
    1: { name: "Feedback", cc: 17 },
    2: { name: "Level", cc: 18 },
    3: { name: "L Damp F", cc: 80 },
    4: { name: "H Damp F", cc: 81 },
    5: { name: "Sync", cc: 82 },
  },
  "Super Filter": {
    0: { name: "Cutoff", cc: 16 },
    1: { name: "Resonance", cc: 17 },
    2: { name: "Flt Type", cc: 18 },
    3: { name: "Depth", cc: 80 },
    4: { name: "Rate", cc: 81 },
    5: { name: "Sync", cc: 82 },
  },
  WrmSaturator: {
    0: { name: "Drive", cc: 16 },
    1: { name: "Eq Low", cc: 17 },
    2: { name: "Eq High", cc: 18 },
    3: { name: "Level", cc: 80 },
  },
  "303 VinylSim": {
    0: { name: "Comp", cc: 16 },
    1: { name: "Noise", cc: 17 },
    2: { name: "Wow Flut", cc: 18 },
    3: { name: "Level", cc: 80 },
  },
  "404 VinylSim": {
    0: { name: "Frequency", cc: 16 },
    1: { name: "Noise", cc: 17 },
    2: { name: "Wow Flut", cc: 18 },
  },
  "Cassette Sim": {
    0: { name: "Tone", cc: 16 },
    1: { name: "Hiss", cc: 17 },
    2: { name: "Age", cc: 18 },
    3: { name: "Drive", cc: 80 },
    4: { name: "Wow Flut", cc: 81 },
    5: { name: "Catch", cc: 82 },
  },
  "Lo-fi": {
    0: { name: "Pre Filt", cc: 16 },
    1: { name: "Lofi Type", cc: 17 },
    2: { name: "Tone", cc: 18 },
    3: { name: "Cutoff", cc: 80 },
    4: { name: "Balance", cc: 81 },
    5: { name: "Level", cc: 82 },
  },
  Reverb: {
    0: { name: "Type", cc: 16 },
    1: { name: "Time", cc: 17 },
    2: { name: "Level", cc: 18 },
    3: { name: "Low Cut", cc: 80 },
    4: { name: "High Cut", cc: 81 },
    5: { name: "Pre Delay", cc: 82 },
  },
  Chorus: {
    0: { name: "Depth", cc: 16 },
    1: { name: "Rate", cc: 17 },
    2: { name: "Balance", cc: 18 },
    3: { name: "Eq Low", cc: 80 },
    4: { name: "Eq High", cc: 81 },
    5: { name: "Level", cc: 82 },
  },
  "JUNO Chorus": {
    0: { name: "Mode", cc: 16 },
    1: { name: "Noise", cc: 17 },
    2: { name: "Balance", cc: 18 },
  },
  Flanger: {
    0: { name: "Depth", cc: 16 },
    1: { name: "Rate", cc: 17 },
    2: { name: "Manual", cc: 18 },
    3: { name: "Resonance", cc: 80 },
    4: { name: "Balance", cc: 81 },
    5: { name: "Sync", cc: 82 },
  },
  Phaser: {
    0: { name: "Depth", cc: 16 },
    1: { name: "Rate", cc: 17 },
    2: { name: "Manual", cc: 18 },
    3: { name: "Resonance", cc: 80 },
    4: { name: "Balance", cc: 81 },
    5: { name: "Sync", cc: 82 },
  },
  Wah: {
    0: { name: "Peak", cc: 16 },
    1: { name: "Rate", cc: 17 },
    2: { name: "Manual", cc: 18 },
    3: { name: "Depth", cc: 80 },
    4: { name: "Flt Type", cc: 81 },
    5: { name: "Sync", cc: 82 },
  },
  Slicer: {
    0: { name: "Pattern", cc: 16 },
    1: { name: "Speed", cc: 17 },
    2: { name: "Depth", cc: 18 },
    3: { name: "Shuffle", cc: 80 },
    4: { name: "Mode", cc: 81 },
    5: { name: "Sync", cc: 82 },
  },
  "Tremolo/Pan": {
    0: { name: "Depth", cc: 16 },
    1: { name: "Rate", cc: 17 },
    2: { name: "Type", cc: 18 },
    3: { name: "Wave", cc: 80 },
    4: { name: "Sync", cc: 81 },
  },
  "Chromatic PS": {
    0: { name: "Pitch 1", cc: 16 },
    1: { name: "Pitch 2", cc: 17 },
    2: { name: "Balance", cc: 18 },
    3: { name: "Pan 1", cc: 80 },
    4: { name: "Pan 2", cc: 81 },
  },
  "Hyper-Reso": {
    0: { name: "Note", cc: 16 },
    1: { name: "Spread", cc: 17 },
    2: { name: "Character", cc: 18 },
    3: { name: "Scale", cc: 80 },
    4: { name: "Feedback", cc: 81 },
    5: { name: "Env Mod", cc: 82 },
  },
  "Ring Mod": {
    0: { name: "Frequency", cc: 16 },
    1: { name: "Sens", cc: 17 },
    2: { name: "Balance", cc: 18 },
    3: { name: "Polarity", cc: 80 },
    4: { name: "Eq Low", cc: 81 },
    5: { name: "Eq High", cc: 82 },
  },
  Crusher: {
    0: { name: "Filter", cc: 16 },
    1: { name: "Rate", cc: 17 },
    2: { name: "Balance", cc: 18 },
  },
  Overdrive: {
    0: { name: "Drive", cc: 16 },
    1: { name: "Tone", cc: 17 },
    2: { name: "Balance", cc: 18 },
    3: { name: "Level", cc: 80 },
  },
  Distortion: {
    0: { name: "Drive", cc: 16 },
    1: { name: "Tone", cc: 17 },
    2: { name: "Balance", cc: 18 },
    3: { name: "Level", cc: 80 },
  },
  Equalizer: {
    0: { name: "Low Gain", cc: 16 },
    1: { name: "Mid Gain", cc: 17 },
    2: { name: "High Gain", cc: 18 },
    3: { name: "Low Freq", cc: 80 },
    4: { name: "Mid Freq", cc: 81 },
    5: { name: "High Freq", cc: 82 },
  },
  Compressor: {
    0: { name: "Sustain", cc: 16 },
    1: { name: "Attack", cc: 17 },
    2: { name: "Ratio", cc: 18 },
    3: { name: "Lev", cc: 80 },
  },
  "SX Reverb": {
    0: { name: "Time", cc: 16 },
    1: { name: "Tone", cc: 17 },
    2: { name: "Balance", cc: 18 },
  },
  "SX Delay": {
    0: { name: "Time", cc: 16 },
    1: { name: "Feedback", cc: 17 },
    2: { name: "Balance", cc: 18 },
  },
  "Cloud Delay": {
    0: { name: "Window", cc: 16 },
    1: { name: "Pitch", cc: 17 },
    2: { name: "Balance", cc: 18 },
    3: { name: "Feedback", cc: 80 },
    4: { name: "Cloudy", cc: 81 },
    5: { name: "Lofi", cc: 82 },
  },
  "Back Spin": {
    0: { name: "Length", cc: 16 },
    1: { name: "Speed", cc: 17 },
    2: { name: "Back Sw", cc: 18 },
  },
  "Auto Pitch": {
    0: { name: "Pitch", cc: 16 },
    1: { name: "Formant", cc: 17 },
    2: { name: "Balance", cc: 18 },
    3: { name: "At Pitch", cc: 80 },
    4: { name: "Key", cc: 81 },
    5: { name: "Robot", cc: 82 },
  },
  Vocoder: {
    0: { name: "Note", cc: 16 },
    1: { name: "Formant", cc: 17 },
    2: { name: "Tone", cc: 18 },
    3: { name: "Scale", cc: 80 },
    4: { name: "Chord", cc: 81 },
    5: { name: "Balance", cc: 82 },
  },
  Harmony: {
    0: { name: "Pitch", cc: 16 },
    1: { name: "Formant", cc: 17 },
    2: { name: "Balance", cc: 18 },
    3: { name: "At Pitch", cc: 80 },
    4: { name: "Key", cc: 81 },
    5: { name: "Harmony", cc: 82 },
  },
  "GT Amp Sim": {
    0: { name: "Amp Type", cc: 16 },
    1: { name: "Drive", cc: 17 },
    2: { name: "Level", cc: 18 },
    3: { name: "Bass", cc: 80 },
    4: { name: "Middle", cc: 81 },
    5: { name: "Treble", cc: 82 },
  },
};
