var data = {
  "(Off)": {},

  "Filter+Drive": {
    0: {
      name: "Cutoff",
      unit: "Hz",
      min: 0,
      max: 16000,
      default: 919,
      cc: 16,
    },
    1: {
      name: "Resonance",
      unit: "",
      min: 0,
      max: 100,
      default: 1,
      cc: 17,
    },
    2: {
      name: "Drive",
      unit: "",
      min: 0,
      max: 100,
      default: 0,
      cc: 18,
    },
    3: {
      name: "Flt Type",
      unit: "enum",
      min: 0,
      max: 1,
      default: 0,
      enum: ["LPF", "HPF"],
      cc: 80,
    },
    4: {
      name: "Low Freq",
      unit: "Hz",
      min: 0,
      max: 16000,
      default: 573,
      cc: 81,
    },
    5: {
      name: "Low Gain",
      unit: "dB",
      min: -24,
      max: 24,
      default: 0,
      cc: 82,
    },
  },
  Resonator: {
    0: {
      name: "Root",
      unit: "note",
      min: 0,
      max: 127,
      default: 40,
      cc: 16,
    },
    1: {
      name: "Bright",
      unit: "",
      min: 0,
      max: 100,
      default: 100,
      cc: 17,
    },
    2: {
      name: "Feedback",
      unit: "%",
      min: 0,
      max: 100,
      default: 38,
      cc: 18,
    },
    3: {
      name: "Chord",
      unit: "enum",
      min: 0,
      max: 15,
      default: 0,
      enum: [
        "Root",
        "Oct",
        "UpDn",
        "P5",
        "m3",
        "m5",
        "m7",
        "m7oct",
        "m0",
        "m11",
        "M3",
        "M5",
        "M7",
        "M7oct",
        "M9",
        "M11",
      ],
      cc: 80,
    },
    4: {
      name: "Panning",
      unit: "",
      min: 0,
      max: 100,
      default: 0,
      cc: 81,
    },
    5: {
      name: "Env Mod",
      unit: "",
      min: 0,
      max: 100,
      default: 48,
      cc: 82,
    },
  },
  "Sync Delay": {
    0: {
      name: "Time",
      unit: "enum",
      min: 0,
      max: 15,
      default: 5,
      enum: [
        "1/32",
        "1/16T",
        "1/32D",
        "1/16",
        "1/8T",
        "1/16D",
        "1/8",
        "1/4T",
        "1/8D",
        "1/4",
        "1/2T",
        "1/4D",
        "1/2",
        "1/1T",
        "1/2D",
        "1/1",
      ],
      cc: 16,
    },
    1: {
      name: "Feedback",
      unit: "%",
      min: 0,
      max: 100,
      default: 49,
      cc: 17,
    },
    2: {
      name: "Level",
      unit: "",
      min: 0,
      max: 100,
      default: 50,
      cc: 18,
    },
    3: {
      name: "L Damp F",
      unit: "Hz",
      min: 0,
      max: 800,
      default: 0,
      cc: 80,
    },
    4: {
      name: "H Damp F",
      unit: "Hz",
      min: 0,
      max: 16000,
      default: 16000,
      cc: 81,
    },
  },
  Isolator: {
    0: {
      name: "Low",
      unit: "dB",
      min: -52,
      max: 12,
      default: -52,
      cc: 16,
    },
    1: {
      name: "Mid",
      unit: "dB",
      min: -52,
      max: 12,
      default: 9,
      cc: 17,
    },
    2: {
      name: "High",
      unit: "dB",
      min: -52,
      max: 12,
      default: -52,
      cc: 18,
    },
  },
  "DJFX Looper": {
    0: {
      name: "Length",
      unit: "sec",
      min: 0.012,
      max: 0.23,
      default: 0.23,
      cc: 16,
    },
    1: {
      name: "Speed",
      unit: "",
      min: 0,
      max: 100,
      default: 100,
      cc: 17,
    },
    2: {
      name: "Loop Sw",
      unit: "",
      min: 0,
      max: 1,
      default: 0,
      cc: 18,
    },
  },
  Scatter: {
    0: {
      name: "Type",
      unit: "",
      min: 1,
      max: 10,
      default: 1,
      cc: 16,
    },
    1: {
      name: "Depth",
      unit: "",
      min: 10,
      max: 100,
      default: 50,
      cc: 17,
    },
    2: {
      name: "Scatter",
      unit: "",
      min: 0,
      max: 1,
      default: 1,
      cc: 18,
    },
    3: {
      name: "Speed",
      unit: "enum",
      min: 0,
      max: 1,
      default: 0,
      enum: ["Single", "Double"],
      cc: 80,
    },
  },
  Downer: {
    0: {
      name: "Depth",
      unit: "",
      min: 0,
      max: 100,
      default: 100,
      cc: 16,
    },
    1: {
      name: "Rate",
      unit: "enum",
      min: 0,
      max: 7,
      default: 1,
      enum: ["2/1", "1/1", "1/2", "1/4", "1/8", "1/16", "1/32"],
      cc: 17,
    },
    2: {
      name: "Filter",
      unit: "",
      min: 0,
      max: 100,
      default: 66,
      cc: 18,
    },
    3: {
      name: "Pitch",
      min: 0,
      max: 1,
      default: 0,
      cc: 80,
    },
    4: {
      name: "Resonance",
      unit: "",
      min: 0,
      max: 100,
      default: 86,
      cc: 81,
    },
  },
  "Ha-Dou": {
    0: {
      name: "Mod Depth",
      unit: "",
      min: 0,
      max: 100,
      default: 100,
      cc: 16,
    },
    1: {
      name: "Time",
      unit: "",
      min: 0,
      max: 100,
      default: 0,
      cc: 17,
    },
    2: {
      name: "Level",
      unit: "",
      min: 0,
      max: 100,
      default: 100,
      cc: 18,
    },
    3: {
      name: "Low Cut",
      unit: "Hz",
      min: 0,
      max: 800,
      default: 0,
      cc: 80,
    },
    4: {
      name: "High Cut",
      unit: "Hz",
      min: 630,
      max: 16000,
      default: 16000,
      cc: 81,
    },
    5: {
      name: "Pre Delay",
      unit: "ms",
      min: 0,
      max: 100,
      default: 100,
      cc: 82,
    },
  },
  "Ko-Da-Ma": {
    0: {
      name: "Time",
      unit: "enum",
      min: 0,
      max: 15,
      default: 5,
      enum: [
        "1/32",
        "1/16T",
        "1/32D",
        "1/16",
        "1/8T",
        "1/16D",
        "1/8",
        "1/4T",
        "1/8D",
        "1/4",
        "1/2T",
        "1/4D",
        "1/2",
        "1/1T",
        "1/2D",
        "1/1",
      ],
      cc: 16,
    },
    1: {
      name: "Feedback",
      unit: "%",
      min: 0,
      max: 100,
      default: 69,
      cc: 17,
    },
    2: {
      name: "Send",
      unit: "",
      min: 0,
      max: 100,
      default: 0,
      cc: 18,
    },
    3: {
      name: "L Damp F",
      unit: "Hz",
      min: 0,
      max: 400,
      default: 0,
      cc: 80,
    },
    4: {
      name: "H Damp F",
      unit: "Hz",
      min: 0,
      max: 12500,
      default: 16000,
      cc: 81,
    },
    5: {
      name: "Mode",
      unit: "enum",
      min: 0,
      max: 1,
      default: 1,
      enum: ["Single", "Pan"],
      cc: 82,
    },
  },
  "Zan-Zou": {
    0: {
      name: "Time",
      unit: "Hz",
      min: 0,
      max: 100,
      default: 53,
      cc: 16,
    },
    1: {
      name: "Feedback",
      unit: "%",
      min: 0,
      max: 99,
      default: 89,
      cc: 17,
    },
    2: {
      name: "HF Damp",
      unit: "Hz",
      min: 200,
      max: 16000,
      default: 16000,
      cc: 18,
    },
    3: {
      name: "Level",
      unit: "",
      min: 0,
      max: 100,
      default: 78,
      cc: 80,
    },
    4: {
      name: "Mode",
      unit: "enum",
      min: 0,
      max: 2,
      default: 0,
      enum: ["2TAP", "3TAP", "4TAP"],
      cc: 81,
    },
    5: {
      name: "Sync",
      unit: "enum",
      min: 0,
      max: 1,
      default: 0,
      enum: ["OFF", "ON"],
      cc: 82,
    },
  },
  "To-Gu-Ro": {
    0: {
      name: "Depth",
      unit: "",
      min: 0,
      max: 100,
      default: 12,
      cc: 16,
    },
    1: {
      name: "Rate",
      unit: "",
      min: 0,
      max: 100,
      default: 25,
      cc: 17,
    },
    2: {
      name: "Resonance",
      unit: "",
      min: 0,
      max: 100,
      default: 50,
      cc: 18,
    },
    3: {
      name: "Flt Mod",
      unit: "",
      min: 0,
      max: 100,
      default: 70,
      cc: 80,
    },
    4: {
      name: "Amp Mod",
      unit: "",
      min: 0,
      max: 100,
      default: 0,
      cc: 81,
    },
    5: {
      name: "Sync",
      unit: "enum",
      min: 0,
      max: 1,
      default: 0,
      enum: ["OFF", "ON"],
      cc: 82,
    },
  },
  SBF: {
    0: {
      name: "Interval",
      unit: "",
      min: 0,
      max: 100,
      default: 0,
      cc: 16,
    },
    1: {
      name: "Width",
      unit: "",
      min: 0,
      max: 100,
      default: 0,
      cc: 17,
    },
    2: {
      name: "Balance",
      unit: "%",
      min: 0,
      max: 100,
      default: 50,
      cc: 18,
    },
    3: {
      name: "Type",
      unit: "enum",
      min: 0,
      max: 5,
      default: 0,
      enum: ["SBF1", "SBF2", "SBF3", "SBF4", "SBF5", "SBF6"],
      cc: 80,
    },
    4: {
      name: "Gain",
      unit: "dB",
      min: -54,
      max: 10,
      default: 0,
      enum: ["OFF", "ON"],
      cc: 81,
    },
  },
  Stopper: {
    0: {
      name: "Depth",
      unit: "",
      min: 0,
      max: 100,
      default: 100,
      cc: 16,
    },
    1: {
      name: "Rate",
      unit: "enum",
      min: 0,
      max: 9,
      default: 2,
      enum: ["4/1", "2/1", "1/1", "1/2", "1/4", "1/8", "1/16", "1/32", "1/64"],
      cc: 17,
    },
    2: {
      name: "Resonance",
      unit: "",
      min: 0,
      max: 100,
      default: 0,
      cc: 18,
    },
    3: {
      name: "Flt Mod",
      unit: "",
      min: 0,
      max: 100,
      default: 0,
      cc: 80,
    },
    4: {
      name: "Amp Mod",
      unit: "",
      min: 0,
      max: 100,
      default: 50,
      cc: 81,
    },
  },
  "Tape Echo": {
    0: {
      name: "Time",
      unit: "ms",
      min: 10,
      max: 800,
      default: 337,
      cc: 16,
    },
    1: {
      name: "Feedback",
      unit: "%",
      min: 0,
      max: 99,
      default: 46,
      cc: 17,
    },
    2: {
      name: "Level",
      unit: "",
      min: 0,
      max: 100,
      default: 50,
      cc: 18,
    },
    3: {
      name: "Mode",
      unit: "enum",
      min: 0,
      max: 7,
      default: 3,
      enum: ["S", "M", "L", "S+M", "S+L", "M+L", "S+M+L"],
      cc: 80,
    },
    4: {
      name: "W/F Rate",
      unit: "",
      min: 0,
      max: 100,
      default: 50,
      cc: 81,
    },
    5: {
      name: "W/F Depth",
      unit: "",
      min: 0,
      max: 100,
      default: 50,
      cc: 82,
    },
  },
  TimeCtrlDly: {
    0: {
      name: "Time",
      cc: 16,
      min: 0,
      max: 127,
      default: 63,
    },
    1: {
      name: "Feedback",
      cc: 17,
      min: 0,
      max: 127,
      default: 63,
    },
    2: {
      name: "Level",
      cc: 18,
      min: 0,
      max: 127,
      default: 63,
    },
    3: {
      name: "L Damp F",
      cc: 80,
      min: 0,
      max: 127,
      default: 63,
    },
    4: {
      name: "H Damp F",
      cc: 81,
      min: 0,
      max: 127,
      default: 63,
    },
    5: {
      name: "Sync",
      cc: 82,
      min: 0,
      max: 127,
      default: 63,
    },
  },
  "Super Filter": {
    0: {
      name: "Cutoff",
      cc: 16,
      min: 0,
      max: 127,
      default: 63,
    },
    1: {
      name: "Resonance",
      cc: 17,
      min: 0,
      max: 127,
      default: 63,
    },
    2: {
      name: "Flt Type",
      cc: 18,
      min: 0,
      max: 127,
      default: 63,
    },
    3: {
      name: "Depth",
      cc: 80,
      min: 0,
      max: 127,
      default: 63,
    },
    4: {
      name: "Rate",
      cc: 81,
      min: 0,
      max: 127,
      default: 63,
    },
    5: {
      name: "Sync",
      cc: 82,
      min: 0,
      max: 127,
      default: 63,
    },
  },
  WrmSaturator: {
    0: {
      name: "Drive",
      cc: 16,
      min: 0,
      max: 127,
      default: 63,
    },
    1: {
      name: "Eq Low",
      cc: 17,
      min: 0,
      max: 127,
      default: 63,
    },
    2: {
      name: "Eq High",
      cc: 18,
      min: 0,
      max: 127,
      default: 63,
    },
    3: {
      name: "Level",
      cc: 80,
      min: 0,
      max: 127,
      default: 63,
    },
  },
  "303 VinylSim": {
    0: {
      name: "Comp",
      cc: 16,
      min: 0,
      max: 127,
      default: 63,
    },
    1: {
      name: "Noise",
      cc: 17,
      min: 0,
      max: 127,
      default: 63,
    },
    2: {
      name: "Wow Flut",
      cc: 18,
      min: 0,
      max: 127,
      default: 63,
    },
    3: {
      name: "Level",
      cc: 80,
      min: 0,
      max: 127,
      default: 63,
    },
  },
  "404 VinylSim": {
    0: {
      name: "Frequency",
      cc: 16,
      min: 0,
      max: 127,
      default: 63,
    },
    1: {
      name: "Noise",
      cc: 17,
      min: 0,
      max: 127,
      default: 63,
    },
    2: {
      name: "Wow Flut",
      cc: 18,
      min: 0,
      max: 127,
      default: 63,
    },
  },
  "Cassette Sim": {
    0: {
      name: "Tone",
      cc: 16,
      min: 0,
      max: 127,
      default: 63,
    },
    1: {
      name: "Hiss",
      cc: 17,
      min: 0,
      max: 127,
      default: 63,
    },
    2: {
      name: "Age",
      cc: 18,
      min: 0,
      max: 127,
      default: 63,
    },
    3: {
      name: "Drive",
      cc: 80,
      min: 0,
      max: 127,
      default: 63,
    },
    4: {
      name: "Wow Flut",
      cc: 81,
      min: 0,
      max: 127,
      default: 63,
    },
    5: {
      name: "Catch",
      cc: 82,
      min: 0,
      max: 127,
      default: 63,
    },
  },
  "Lo-fi": {
    0: {
      name: "Pre Filt",
      cc: 16,
      min: 0,
      max: 127,
      default: 63,
    },
    1: {
      name: "Lofi Type",
      cc: 17,
      min: 0,
      max: 127,
      default: 63,
    },
    2: {
      name: "Tone",
      cc: 18,
      min: 0,
      max: 127,
      default: 63,
    },
    3: {
      name: "Cutoff",
      cc: 80,
      min: 0,
      max: 127,
      default: 63,
    },
    4: {
      name: "Balance",
      cc: 81,
      min: 0,
      max: 127,
      default: 63,
    },
    5: {
      name: "Level",
      cc: 82,
      min: 0,
      max: 127,
      default: 63,
    },
  },
  Reverb: {
    0: {
      name: "Type",
      cc: 16,
      min: 0,
      max: 127,
      default: 63,
    },
    1: {
      name: "Time",
      cc: 17,
      min: 0,
      max: 127,
      default: 63,
    },
    2: {
      name: "Level",
      cc: 18,
      min: 0,
      max: 127,
      default: 63,
    },
    3: {
      name: "Low Cut",
      cc: 80,
      min: 0,
      max: 127,
      default: 63,
    },
    4: {
      name: "High Cut",
      cc: 81,
      min: 0,
      max: 127,
      default: 63,
    },
    5: {
      name: "Pre Delay",
      cc: 82,
      min: 0,
      max: 127,
      default: 63,
    },
  },
  Chorus: {
    0: {
      name: "Depth",
      cc: 16,
      min: 0,
      max: 127,
      default: 63,
    },
    1: {
      name: "Rate",
      cc: 17,
      min: 0,
      max: 127,
      default: 63,
    },
    2: {
      name: "Balance",
      cc: 18,
      min: 0,
      max: 127,
      default: 63,
    },
    3: {
      name: "Eq Low",
      cc: 80,
      min: 0,
      max: 127,
      default: 63,
    },
    4: {
      name: "Eq High",
      cc: 81,
      min: 0,
      max: 127,
      default: 63,
    },
    5: {
      name: "Level",
      cc: 82,
      min: 0,
      max: 127,
      default: 63,
    },
  },
  "JUNO Chorus": {
    0: {
      name: "Mode",
      cc: 16,
      min: 0,
      max: 127,
      default: 63,
    },
    1: {
      name: "Noise",
      cc: 17,
      min: 0,
      max: 127,
      default: 63,
    },
    2: {
      name: "Balance",
      cc: 18,
      min: 0,
      max: 127,
      default: 63,
    },
  },
  Flanger: {
    0: {
      name: "Depth",
      cc: 16,
      min: 0,
      max: 127,
      default: 63,
    },
    1: {
      name: "Rate",
      cc: 17,
      min: 0,
      max: 127,
      default: 63,
    },
    2: {
      name: "Manual",
      cc: 18,
      min: 0,
      max: 127,
      default: 63,
    },
    3: {
      name: "Resonance",
      cc: 80,
      min: 0,
      max: 127,
      default: 63,
    },
    4: {
      name: "Balance",
      cc: 81,
      min: 0,
      max: 127,
      default: 63,
    },
    5: {
      name: "Sync",
      cc: 82,
      min: 0,
      max: 127,
      default: 63,
    },
  },
  Phaser: {
    0: {
      name: "Depth",
      cc: 16,
      min: 0,
      max: 127,
      default: 63,
    },
    1: {
      name: "Rate",
      cc: 17,
      min: 0,
      max: 127,
      default: 63,
    },
    2: {
      name: "Manual",
      cc: 18,
      min: 0,
      max: 127,
      default: 63,
    },
    3: {
      name: "Resonance",
      cc: 80,
      min: 0,
      max: 127,
      default: 63,
    },
    4: {
      name: "Balance",
      cc: 81,
      min: 0,
      max: 127,
      default: 63,
    },
    5: {
      name: "Sync",
      cc: 82,
      min: 0,
      max: 127,
      default: 63,
    },
  },
  Wah: {
    0: {
      name: "Peak",
      cc: 16,
      min: 0,
      max: 127,
      default: 63,
    },
    1: {
      name: "Rate",
      cc: 17,
      min: 0,
      max: 127,
      default: 63,
    },
    2: {
      name: "Manual",
      cc: 18,
      min: 0,
      max: 127,
      default: 63,
    },
    3: {
      name: "Depth",
      cc: 80,
      min: 0,
      max: 127,
      default: 63,
    },
    4: {
      name: "Flt Type",
      cc: 81,
      min: 0,
      max: 127,
      default: 63,
    },
    5: {
      name: "Sync",
      cc: 82,
      min: 0,
      max: 127,
      default: 63,
    },
  },
  Slicer: {
    0: {
      name: "Pattern",
      cc: 16,
      min: 0,
      max: 127,
      default: 63,
    },
    1: {
      name: "Speed",
      cc: 17,
      min: 0,
      max: 127,
      default: 63,
    },
    2: {
      name: "Depth",
      cc: 18,
      min: 0,
      max: 127,
      default: 63,
    },
    3: {
      name: "Shuffle",
      cc: 80,
      min: 0,
      max: 127,
      default: 63,
    },
    4: {
      name: "Mode",
      cc: 81,
      min: 0,
      max: 127,
      default: 63,
    },
    5: {
      name: "Sync",
      cc: 82,
      min: 0,
      max: 127,
      default: 63,
    },
  },
  "Tremolo/Pan": {
    0: {
      name: "Depth",
      cc: 16,
      min: 0,
      max: 127,
      default: 63,
    },
    1: {
      name: "Rate",
      cc: 17,
      min: 0,
      max: 127,
      default: 63,
    },
    2: {
      name: "Type",
      cc: 18,
      min: 0,
      max: 127,
      default: 63,
    },
    3: {
      name: "Wave",
      cc: 80,
      min: 0,
      max: 127,
      default: 63,
    },
    4: {
      name: "Sync",
      cc: 81,
      min: 0,
      max: 127,
      default: 63,
    },
  },
  "Chromatic PS": {
    0: {
      name: "Pitch 1",
      cc: 16,
      min: 0,
      max: 127,
      default: 63,
    },
    1: {
      name: "Pitch 2",
      cc: 17,
      min: 0,
      max: 127,
      default: 63,
    },
    2: {
      name: "Balance",
      cc: 18,
      min: 0,
      max: 127,
      default: 63,
    },
    3: {
      name: "Pan 1",
      cc: 80,
      min: 0,
      max: 127,
      default: 63,
    },
    4: {
      name: "Pan 2",
      cc: 81,
      min: 0,
      max: 127,
      default: 63,
    },
  },
  "Hyper-Reso": {
    0: {
      name: "Note",
      cc: 16,
      min: 0,
      max: 127,
      default: 63,
    },
    1: {
      name: "Spread",
      cc: 17,
      min: 0,
      max: 127,
      default: 63,
    },
    2: {
      name: "Character",
      cc: 18,
      min: 0,
      max: 127,
      default: 63,
    },
    3: {
      name: "Scale",
      cc: 80,
      min: 0,
      max: 127,
      default: 63,
    },
    4: {
      name: "Feedback",
      cc: 81,
      min: 0,
      max: 127,
      default: 63,
    },
    5: {
      name: "Env Mod",
      cc: 82,
      min: 0,
      max: 127,
      default: 63,
    },
  },
  "Ring Mod": {
    0: {
      name: "Frequency",
      cc: 16,
      min: 0,
      max: 127,
      default: 63,
    },
    1: {
      name: "Sens",
      cc: 17,
      min: 0,
      max: 127,
      default: 63,
    },
    2: {
      name: "Balance",
      cc: 18,
      min: 0,
      max: 127,
      default: 63,
    },
    3: {
      name: "Polarity",
      cc: 80,
      min: 0,
      max: 127,
      default: 63,
    },
    4: {
      name: "Eq Low",
      cc: 81,
      min: 0,
      max: 127,
      default: 63,
    },
    5: {
      name: "Eq High",
      cc: 82,
      min: 0,
      max: 127,
      default: 63,
    },
  },
  Crusher: {
    0: {
      name: "Filter",
      cc: 16,
      min: 0,
      max: 127,
      default: 63,
    },
    1: {
      name: "Rate",
      cc: 17,
      min: 0,
      max: 127,
      default: 63,
    },
    2: {
      name: "Balance",
      cc: 18,
      min: 0,
      max: 127,
      default: 63,
    },
  },
  Overdrive: {
    0: {
      name: "Drive",
      cc: 16,
      min: 0,
      max: 127,
      default: 63,
    },
    1: {
      name: "Tone",
      cc: 17,
      min: 0,
      max: 127,
      default: 63,
    },
    2: {
      name: "Balance",
      cc: 18,
      min: 0,
      max: 127,
      default: 63,
    },
    3: {
      name: "Level",
      cc: 80,
      min: 0,
      max: 127,
      default: 63,
    },
  },
  Distortion: {
    0: {
      name: "Drive",
      cc: 16,
      min: 0,
      max: 127,
      default: 63,
    },
    1: {
      name: "Tone",
      cc: 17,
      min: 0,
      max: 127,
      default: 63,
    },
    2: {
      name: "Balance",
      cc: 18,
      min: 0,
      max: 127,
      default: 63,
    },
    3: {
      name: "Level",
      cc: 80,
      min: 0,
      max: 127,
      default: 63,
    },
  },
  Equalizer: {
    0: {
      name: "Low Gain",
      cc: 16,
      min: 0,
      max: 127,
      default: 63,
    },
    1: {
      name: "Mid Gain",
      cc: 17,
      min: 0,
      max: 127,
      default: 63,
    },
    2: {
      name: "High Gain",
      cc: 18,
      min: 0,
      max: 127,
      default: 63,
    },
    3: {
      name: "Low Freq",
      cc: 80,
      min: 0,
      max: 127,
      default: 63,
    },
    4: {
      name: "Mid Freq",
      cc: 81,
      min: 0,
      max: 127,
      default: 63,
    },
    5: {
      name: "High Freq",
      cc: 82,
      min: 0,
      max: 127,
      default: 63,
    },
  },
  Compressor: {
    0: {
      name: "Sustain",
      cc: 16,
      min: 0,
      max: 127,
      default: 63,
    },
    1: {
      name: "Attack",
      cc: 17,
      min: 0,
      max: 127,
      default: 63,
    },
    2: {
      name: "Ratio",
      cc: 18,
      min: 0,
      max: 127,
      default: 63,
    },
    3: {
      name: "Lev",
      cc: 80,
      min: 0,
      max: 127,
      default: 63,
    },
  },
  "SX Reverb": {
    0: {
      name: "Time",
      cc: 16,
      min: 0,
      max: 127,
      default: 63,
    },
    1: {
      name: "Tone",
      cc: 17,
      min: 0,
      max: 127,
      default: 63,
    },
    2: {
      name: "Balance",
      cc: 18,
      min: 0,
      max: 127,
      default: 63,
    },
  },
  "SX Delay": {
    0: {
      name: "Time",
      cc: 16,
      min: 0,
      max: 127,
      default: 63,
    },
    1: {
      name: "Feedback",
      cc: 17,
      min: 0,
      max: 127,
      default: 63,
    },
    2: {
      name: "Balance",
      cc: 18,
      min: 0,
      max: 127,
      default: 63,
    },
  },
  "Cloud Delay": {
    0: {
      name: "Window",
      cc: 16,
      min: 0,
      max: 127,
      default: 63,
    },
    1: {
      name: "Pitch",
      cc: 17,
      min: 0,
      max: 127,
      default: 63,
    },
    2: {
      name: "Balance",
      cc: 18,
      min: 0,
      max: 127,
      default: 63,
    },
    3: {
      name: "Feedback",
      cc: 80,
      min: 0,
      max: 127,
      default: 63,
    },
    4: {
      name: "Cloudy",
      cc: 81,
      min: 0,
      max: 127,
      default: 63,
    },
    5: {
      name: "Lofi",
      cc: 82,
      min: 0,
      max: 127,
      default: 63,
    },
  },
  "Back Spin": {
    0: {
      name: "Length",
      cc: 16,
      min: 0,
      max: 127,
      default: 63,
    },
    1: {
      name: "Speed",
      cc: 17,
      min: 0,
      max: 127,
      default: 63,
    },
    2: {
      name: "Back Sw",
      cc: 18,
      min: 0,
      max: 127,
      default: 63,
    },
  },
  "Auto Pitch": {
    0: {
      name: "Pitch",
      cc: 16,
      min: 0,
      max: 127,
      default: 63,
    },
    1: {
      name: "Formant",
      cc: 17,
      min: 0,
      max: 127,
      default: 63,
    },
    2: {
      name: "Balance",
      cc: 18,
      min: 0,
      max: 127,
      default: 63,
    },
    3: {
      name: "At Pitch",
      cc: 80,
      min: 0,
      max: 127,
      default: 63,
    },
    4: {
      name: "Key",
      cc: 81,
      min: 0,
      max: 127,
      default: 63,
    },
    5: {
      name: "Robot",
      cc: 82,
      min: 0,
      max: 127,
      default: 63,
    },
  },
  Vocoder: {
    0: {
      name: "Note",
      cc: 16,
      min: 0,
      max: 127,
      default: 63,
    },
    1: {
      name: "Formant",
      cc: 17,
      min: 0,
      max: 127,
      default: 63,
    },
    2: {
      name: "Tone",
      cc: 18,
      min: 0,
      max: 127,
      default: 63,
    },
    3: {
      name: "Scale",
      cc: 80,
      min: 0,
      max: 127,
      default: 63,
    },
    4: {
      name: "Chord",
      cc: 81,
      min: 0,
      max: 127,
      default: 63,
    },
    5: {
      name: "Balance",
      cc: 82,
      min: 0,
      max: 127,
      default: 63,
    },
  },
  Harmony: {
    0: {
      name: "Pitch",
      cc: 16,
      min: 0,
      max: 127,
      default: 63,
    },
    1: {
      name: "Formant",
      cc: 17,
      min: 0,
      max: 127,
      default: 63,
    },
    2: {
      name: "Balance",
      cc: 18,
      min: 0,
      max: 127,
      default: 63,
    },
    3: {
      name: "At Pitch",
      cc: 80,
      min: 0,
      max: 127,
      default: 63,
    },
    4: {
      name: "Key",
      cc: 81,
      min: 0,
      max: 127,
      default: 63,
    },
    5: {
      name: "Harmony",
      cc: 82,
      min: 0,
      max: 127,
      default: 63,
    },
  },
  "GT Amp Sim": {
    0: {
      name: "Amp Type",
      cc: 16,
      min: 0,
      max: 127,
      default: 63,
    },
    1: {
      name: "Drive",
      cc: 17,
      min: 0,
      max: 127,
      default: 63,
    },
    2: {
      name: "Level",
      cc: 18,
      min: 0,
      max: 127,
      default: 63,
    },
    3: {
      name: "Bass",
      cc: 80,
      min: 0,
      max: 127,
      default: 63,
    },
    4: {
      name: "Middle",
      cc: 81,
      min: 0,
      max: 127,
      default: 63,
    },
    5: {
      name: "Treble",
      cc: 82,
      min: 0,
      max: 127,
      default: 63,
    },
  },
};

outlets = 12; // 0-5 is for Ctrl labels, 6-11 is for labels in ext. window
var labels = ["C1", "C2", "C3", "C4", "C5", "C6"];
var fxTypes = ["", "", "", "", "", "", ""];
var directFxTypes = [
  "Filter+Drive",
  "Resonator",
  "Sync Delay",
  "Isolator",
  "DJFX Looper",
];

var module = 0; // 0 = off / 1-6 FX modules

function bang() {
  for (var i = 0; i <= 5; i++) {
    outlet(i, ["set", labels[i]]);
  }
  for (var j = 6; j <= 11; j++) {
    if (!startsWith(fxTypes[j - 6], "Direct")) {
      outlet(j, ["set", fxTypes[j - 6]]);
    } else {
      var directFxNumber = parseInt(fxTypes[j - 6].slice(-1)) - 1; // get last character (Direct FX number)
      outlet(j, ["set", directFxTypes[directFxNumber]]);
    }
  }
}

function update() {
  var currentFxName;
  if (startsWith(fxTypes[module], "Direct")) {
    var directFxNumber = parseInt(fxTypes[module].slice(-1)) - 1;
    currentFxName = directFxTypes[directFxNumber];
  } else {
    currentFxName = fxTypes[module];
  }

  for (var i = 0; i < labels.length; i++) {
    var fxParam = data[currentFxName];
    if (fxParam && fxParam[i] && fxParam[i].name) {
      labels[i] = fxParam[i].name;
    } else {
      labels[i] = "---";
    }
  }
  bang();
}

function setFxModule(lastActivatedFx) {
  // post("last activated: ", lastActivatedFx);
  module = lastActivatedFx;
  update();
}

function setFxType(fxModule, fxName) {
  // post(fxModule, fxName);
  fxTypes[fxModule] = fxName;
  update();
}

function setDirectFx(directFxNum, fxType) {
  directFxTypes[directFxNum] = fxType;
  update();
}

// ES5 alternative for ES6 .startsWith()
function startsWith(str, word) {
  return str.lastIndexOf(word, 0) === 0;
}
